version: '3.9'
services:
    jupyter:
        container_name: SalesDataScience
        build:
            context: ./docker
            dockerfile: Dockerfile
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - JUPYTER_ENABLE_LAB=yes
        entrypoint: >
            jupyter-lab
                --allow-root
                --ip=0.0.0.0
                --port=8888
                --no-browser
                --NotebookApp.token='TOKEN'
                --notebook-dir=/workspace
        volumes: 
            - .:/workspace
            - ./py3/root_jupyter:/root/.jupyter
        ports:
            - 8888:8888
        tty: true